name: Build DEV - Frontend

on:
  push:
    branches:
      - "develop"
      - 'releases/**'
    paths-ignore:
      - "README.md"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-frontend-ci:
    runs-on: ubuntu-latest
    name: build&deploy

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: ğŸ•µï¸â€â™‚ï¸ Get latest code
        uses: actions/checkout@v3

      - name: ğŸš€ Deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'root'
          server: '${{ secrets.REMOTE_HOST }}'
          ssh_private_key: ${{ secrets.REMOTE_KEY }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './'
          remote_path: ${{ secrets.FTP_PATH }}
          sftpArgs: '-o ConnectTimeout=5'
          sftp_only: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ³ Docker build container
        run: docker build -t craftscript_fe .

      - name: ğŸ³ Run Docker container
        run: docker run -d -p 3000:3000 craftscript_fe