name: Build DEV - Frontend

on:
  push:
    branches:
      - "develop"
    paths-ignore:
      - "README.md"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-frontend-ci:
    runs-on: ubuntu-latest
    name: build&deploy&run

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: üöö Get latest code
        uses: actions/checkout@v3

      - name: üöÄ Deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'root'
          server: '${{ secrets.REMOTE_HOST }}'
          ssh_private_key: ${{ secrets.REMOTE_KEY }}
          password: ${{  secrets.FTP_PASSWORD }}
          local_path: './*'
          remote_path: ${{ secrets.FTP_PATH }}
          sftpArgs: '-o ConnectTimeout=5'
          sftp_only: true
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            fileToExclude.txt

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Installing frontend dependencies
        run: |
          npm install
          ls -al

      - name: Building frontend
        env:
          REACT_APP_BACKEND_URL: "https://api.craftscript.com/"
        run: |
          rm .env
          CI=false npm run build
          ls -al ./.next

      - name: üèÅ Run frontend
        run: |
          npm start